# https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/

global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: francescocalzona82@gmail.com
    from: francescocalzona82@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: francescocalzona82@gmail.com
    auth_identity: francescocalzona82@gmail.com
    auth_password: #my gmail app password
    send_resolved: true